// Code generated by https://github.com/zhufuyi/sponge

package routers

import (
	"context"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc/metadata"

	"github.com/zhufuyi/sponge/pkg/gin/middleware"
	"github.com/zhufuyi/sponge/pkg/logger"

	gatewayV1 "gateway/api/gateway/v1"
	"gateway/internal/service"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
		dataVisualizationMiddlewares(c)
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
			dataVisualizationRouter(r, groupPathMiddlewares, singlePathMiddlewares, service.NewDataVisualizationClient())
		})
}

func dataVisualizationRouter(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService gatewayV1.DataVisualizationLogicer) {
	ctxFn := func(c *gin.Context) context.Context {
		md := metadata.New(map[string]string{
			// set metadata to be passed from http to rpc
			middleware.ContextRequestIDKey: middleware.GCtxRequestID(c), // request_id
			//middleware.HeaderAuthorizationKey: c.GetHeader(middleware.HeaderAuthorizationKey),  // authorization
		})
		return metadata.NewOutgoingContext(c.Request.Context(), md)
	}

	gatewayV1.RegisterDataVisualizationRouter(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		gatewayV1.WithDataVisualizationLogger(logger.Get()),
		gatewayV1.WithDataVisualizationRPCResponse(),
		gatewayV1.WithDataVisualizationWrapCtx(ctxFn),
		gatewayV1.WithDataVisualizationRPCStatusToHTTPCode(
		// Set some error codes to standard http return codes,
		// by default there is already ecode.StatusInternalServerError and ecode.StatusServiceUnavailable
		// example:
		// 	ecode.StatusUnimplemented, ecode.StatusAborted,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route,
// or you can mix them, pay attention to the duplication of middleware when mixing them,
// it is recommended to set the middleware of a single route in preference
func dataVisualizationMiddlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/dataVisualization/:id  will take effect
	// c.setGroupPath("/api/v1/dataVisualization", middleware.Auth())

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
	//c.setSinglePath("POST", "/api/v1/dataVisualization/getDeviceData", middleware.Auth())
	c.setGroupPath("/api/v1/device", jwtToken.JWTAuth(), authority.ApiAuth())

	c.setSinglePath("GET", "/api/v1/device/dataPush", websocket.Upgrade(func(ctx *gin.Context) (res interface{}, err error) {
		//c.setSinglePath("POST", "/api/v1/dataVisualization/chart", middleware.Auth())
		//c.setSinglePath("POST", "/api/v1/device/chart", middleware.Auth())
		return "123", nil
	}))
}
