// Code generated by https://github.com/zhufuyi/sponge

package ecode

import (
	"github.com/zhufuyi/sponge/pkg/errcode"
)

// dataVisualization business-level rpc error codes.
// the _dataVisualizationNO value range is 1~100, if the same number appears, it will cause a failure to start the service.
var (
	_dataVisualizationNO       = 50
	_dataVisualizationName     = "dataVisualization"
	_dataVisualizationBaseCode = errcode.RCode(_dataVisualizationNO)

	StatusDeviceDataGetDataVisualization   = errcode.NewRPCStatus(_dataVisualizationBaseCode+1, "failed to DeviceDataGet "+_dataVisualizationName)
	StatusDeviceDataCurveDataVisualization = errcode.NewRPCStatus(_dataVisualizationBaseCode+2, "failed to DeviceDataCurve "+_dataVisualizationName)
	// error codes are globally unique, adding 1 to the previous error code
)
