apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: gateway
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: gateway-svc-http-port
      port: 8080
      targetPort: 8080

