apiVersion: v1
kind: Service
metadata:
  name: manager-svc
  namespace: manager
spec:
  selector:
    app: manager
  type: ClusterIP
  ports:
    - name: manager-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: manager-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

