// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/common/common.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DataDetail with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DataDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DataDetailMultiError, or
// nil if none found.
func (m *DataDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *DataDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Value

	// no validation rules for Unit

	if len(errors) > 0 {
		return DataDetailMultiError(errors)
	}

	return nil
}

// DataDetailMultiError is an error wrapping multiple validation errors
// returned by DataDetail.ValidateAll() if the designated constraints aren't met.
type DataDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataDetailMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataDetailMultiError) AllErrors() []error { return m }

// DataDetailValidationError is the validation error returned by
// DataDetail.Validate if the designated constraints aren't met.
type DataDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataDetailValidationError) ErrorName() string { return "DataDetailValidationError" }

// Error satisfies the builtin error interface
func (e DataDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataDetailValidationError{}

// Validate checks the field values on DeviceData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeviceData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeviceData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeviceDataMultiError, or
// nil if none found.
func (m *DeviceData) ValidateAll() error {
	return m.validate(true)
}

func (m *DeviceData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DeviceDataValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DeviceDataValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DeviceDataValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return DeviceDataMultiError(errors)
	}

	return nil
}

// DeviceDataMultiError is an error wrapping multiple validation errors
// returned by DeviceData.ValidateAll() if the designated constraints aren't met.
type DeviceDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceDataMultiError) AllErrors() []error { return m }

// DeviceDataValidationError is the validation error returned by
// DeviceData.Validate if the designated constraints aren't met.
type DeviceDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceDataValidationError) ErrorName() string { return "DeviceDataValidationError" }

// Error satisfies the builtin error interface
func (e DeviceDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceDataValidationError{}
